const socials = [
  {
    title: "Website",
    url: true,
    userName: false,
    phone: false,
    socialid: false,
    icon: "images/socialicons/web.svg",
  },
  {
    title: "9gag",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/9gag.svg",
    link: "https://9gag.com/u/",
  },
  {
    title: "Snapchat",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/snapchat.svg",
    link: "https://www.snapchat.com/add/",
  },
  {
    title: "Instagram",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/insta.png",
    link: "https://www.instagram.com/",
  },
  {
    title: "Medium",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/mediumlogo.svg",
    link: "https://medium.com/",
  },
  {
    title: "TikTok",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/tiktok.svg",
    link: "https://tiktok.com/@",
  },
  {
    title: "Youtube",
    url: true,
    userName: false,
    socialid: false,
    phone: false,
    icon: "images/socialicons/youtube.svg",
  },
  {
    title: "Facebook",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/facebook.svg",
    link: "https://www.facebook.com/",
  },
  {
    title: "Twitter",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/twitter.svg",
    link: "https://twitter.com/",
  },
  {
    title: "Twitch",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/twitch.svg",
    link: "https://www.twitch.tv/",
  },
  {
    title: "Pinterest",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/pinterest.svg",
    link: "https://www.pinterest.se/",
  },
  {
    title: "Github",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/github.svg",
    link: "https://github.com/",
  },
  {
    title: "Reddit",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/reddit.svg",
    link: "https://www.reddit.com/user/",
  },
  {
    title: "Soundcloud",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/soundcloud.svg",
    link: "https://soundcloud.com/",
  },
  {
    title: "Vk",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/vk.svg",
    link: "https://vk.com/",
  },
  {
    title: "Ask.Fm",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/askfm.svg",
    link: "https://ask.fm/",
  },
  {
    title: "Flickr",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/flickr.svg",
    link: "https://www.flickr.com/",
  },
  {
    title: "Odnoklassniki",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/odnoklassniki.svg",
    link: "https://ok.ru/",
  },
  {
    title: "Discord",
    url: true,
    userName: false,
    phone: false,
    socialid: false,
    icon: "images/socialicons/discord.svg",
  },
  {
    title: "Tripadvisor",
    url: true,
    userName: false,
    phone: false,
    socialid: false,
    icon: "images/socialicons/tripadvisor.svg",
  },
  {
    title: "Telegram",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/telegram.svg",
    link: "https://t.me/",
  },
  {
    title: "Patreon",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/patreon.svg",
    link: "https://www.patreon.com/",
  },
  {
    title: "Youtube Music",
    url: true,
    userName: false,
    phone: false,
    socialid: false,
    icon: "images/socialicons/youtubemusic.svg",
  },
  {
    title: "Deezer",
    url: true,
    userName: false,
    phone: false,
    socialid: false,
    icon: "images/socialicons/deezer.svg",
  },
  {
    title: "TuneIn",
    url: true,
    userName: false,
    phone: false,
    socialid: false,
    icon: "images/socialicons/tunein.svg",
  },
  {
    title: "Slack",
    url: true,
    userName: false,
    phone: false,
    socialid: false,
    icon: "images/socialicons/slacklogo.svg",
  },
  {
    title: "WhatsApp",
    url: false,
    userName: false,
    phone: true,
    socialid: false,
    icon: "images/socialicons/whatsapp.svg",
  },
  {
    title: "WeChat",
    url: false,
    userName: false,
    phone: false,
    socialid: true,
    icon: "images/socialicons/wechat.svg",
  },
  {
    title: "Stitcher",
    url: true,
    userName: false,
    phone: false,
    socialid: false,
    icon: "images/socialicons/stitcher.svg",
  },
  {
    title: "Skype",
    url: false,
    userName: false,
    phone: false,
    socialid: true,
    icon: "images/socialicons/skypelogo.svg",
  },
  {
    title: "Blogg",
    url: true,
    userName: false,
    phone: false,
    socialid: false,
    icon: "images/socialicons/blogg.svg",
  },
  {
    title: "Onlyfans",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/onlyfanslogo.svg",
    link: "https://onlyfans.com/",
  },
  {
    title: "Cameo",
    url: false,
    userName: true,
    phone: false,
    socialid: false,
    icon: "images/socialicons/cameo.svg",
    link: "https://cameo.com/",
  },
  {
    title: "Spotify",
    url: true,
    userName: false,
    phone: false,
    socialid: false,
    icon: "images/socialicons/spotify.svg"
  },
  {
    title: "LinkedIn",
    url: true,
    userName: false,
    phone: false,
    socialid: false,
    icon: "images/socialicons/linkedin.svg"
  },
  {
    title: "Origin",
    url: false,
    userName: false,
    phone: false,
    socialid: true,
    icon: "images/socialicons/origin.svg"
  },
  {
    title: "Steam",
    url: false,
    userName: false,
    phone: false,
    socialid: true,
    icon: "images/socialicons/steam.svg"
  }
];

module.exports = {
  socials: socials,
};
