//NOTIFICATIONS
export const SHOW_NOTIFICATION = "[Notification] Show Notification";
export const HIDE_NOTIFICATION = "[Notification] Hide Notification";



//AUTH
export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const LOGIN_START = "[Auth] Login Start";
export const LOGIN_SUCCESS = "[Auth] Login Success";
export const LOGIN_FAILURE = "[Auth] Login Failed";
export const LOGOUT = "[Auth] Logout";



//SOCIALS
export const GET_SOCIALS_LIST = "GET_SOCIALS_LIST";
export const GET_SOCIALS_LIST_SUCCESS = "GET_SOCIALS_LIST_SUCCESS";
export const GET_SOCIALS_LIST_FAILURE = "GET_SOCIALS_LIST_FAILURE";
export const GET_SOCIAL = "GET_SOCIAL";
export const GET_SOCIAL_SUCCESS = "GET_SOCIAL_SUCCESS";
export const GET_SOCIAL_FAILURE = "GET_SOCIAL_FAILURE"
export const SOCIALS_CREATED_SUCCESS = "SOCIALS_CREATED_SUCCESS";
export const SOCIALS_CREATED_FAILED = "SOCIALS_CREATED_FAILED";
export const DELETE_SOCIAL = "DELETE_SOCIAL"
export const DELETE_SOCIAL_SUCCESS = "DELETE_SOCIAL_SUCCESS"
export const DELETE_SOCIAL_FAILURE = "DELETE_SOCIAL_FAILURE"
export const CREATE_SOCIAL = "DELETE_SOCIAL"
export const CREATE_SOCIAL_SUCCESS = "DELETE_SOCIAL_SUCCESS"
export const CREATE_SOCIAL_FAILURE = "DELETE_SOCIAL_FAILURE"
export const UPDATE_SOCIAL_SUCCESS = "UPDATE_SOCIAL_SUCCESS"
export const UPDATE_SOCIAL_FAILURE = "UPDATE_SOCIAL_FAILURE"
export const UPDATE_SOCIAL = "UPDATE_SOCIAL"



//PUBLIC
export const GET_PUBLIC_SOCIALS_LIST_SUCCESS = "GET_PUBLIC_SOCIALS_LIST_SUCCESS"
export const GET_PUBLIC_SOCIALS_LIST_FAILURE = "GET_PUBLIC_SOCIALS_LIST_FAILURE"
export const VERIFY_USER_SUCCESS = "VERIFY_USER_SUCCESS"
export const VERIFY_USER_FAILED = "VERIFY_USER_FAILED"
export const GET_PUBLIC_QRCODE_SUCCESS = "GET_PUBLIC_QRCODE_SUCCESS"
export const GET_PUBLIC_QRCODE_FAILURE = "GET_PUBLIC_QRCODE_FAILURE"



//USER
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE"
export const USER_UPDATE_PASSWORD_SUCCESS = "USER_UPDATE_PASSWORD_SUCCESS"
export const USER_UPDATE_PASSWORD_FAILURE = "USER_UPDATE_PASSWORD_FAILURE"
export const USER_UPDATE_USERNAME_SUCCESS = "USER_UPDATE_USERNAME_SUCCESS"
export const USER_UPDATE_USERNAME_FAILURE = "USER_UPDATE_USERNAME_FAILURE"
export const GET_USER_PUBLIC_DATA_SUCCESS = "GET_USER_PUBLIC_DATA_SUCCESS"
export const GET_USER_PUBLIC_DATA_FAILURE = "GET_USER_PUBLIC_DATA_FAILURE"


